import type { Database } from "@/types/database";

type Jugador = Database["public"]["Tables"]["jugadores"]["Row"];
type Equipo = Database["public"]["Tables"]["equipos"]["Row"];

export const mockJugadores: Jugador[] = [
  {
    id: "j1",
    user_id: "u1",
    discord_id: "1234567890",
    discord_username: "Shaiiko#0001",
    discord_avatar: "https://cdn.discordapp.com/embed/avatars/1.png",
    ubisoft_id: "Shaiiko.BDS",
    rango: "Champion",
    kd: 1.45,
    rol_principal: "entry-fragger",
    rol_secundario: "roamer",
    disponibilidad: "solo-competitivo",
    region: "eu-west",
    idioma: "fr/en",
    plataforma: "pc",
    destacado: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "j2",
    user_id: "u2",
    discord_id: "2345678901",
    discord_username: "Spoit#0002",
    discord_avatar: "https://cdn.discordapp.com/embed/avatars/2.png",
    ubisoft_id: "Spoit.M80",
    rango: "Diamond II",
    kd: 1.35,
    rol_principal: "entry-fragger",
    rol_secundario: "flex",
    disponibilidad: "diaria",
    region: "na",
    idioma: "en/sv",
    plataforma: "pc",
    destacado: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "j3",
    user_id: "u3",
    discord_id: "3456789012",
    discord_username: "Goga#0003",
    discord_avatar: "https://cdn.discordapp.com/embed/avatars/3.png",
    ubisoft_id: "Goga.PENTA",
    rango: "Diamond IV",
    kd: 1.05,
    rol_principal: "support",
    rol_secundario: "hard-breach",
    disponibilidad: "flexible",
    region: "eu-west",
    idioma: "es/en",
    plataforma: "pc",
    destacado: false,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "j4",
    user_id: "u4",
    discord_id: "4567890123",
    discord_username: "Tobi#9999",
    discord_avatar: "https://cdn.discordapp.com/embed/avatars/4.png",
    ubisoft_id: "TobiasSiege",
    rango: "Gold I",
    kd: 1.12,
    rol_principal: "anchor",
    rol_secundario: "intel",
    disponibilidad: "fines-de-semana",
    region: "latam",
    idioma: "es",
    plataforma: "playstation",
    destacado: false,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "j5",
    user_id: "u5",
    discord_id: "5678901234",
    discord_username: "Pengu#0007",
    discord_avatar: "https://cdn.discordapp.com/embed/avatars/0.png",
    ubisoft_id: "Pengu.G2",
    rango: "Champion",
    kd: 1.25,
    rol_principal: "flex",
    rol_secundario: "intel",
    disponibilidad: "solo-competitivo",
    region: "eu-west",
    idioma: "en/da",
    plataforma: "pc",
    destacado: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "j6",
    user_id: "u6",
    discord_id: "6789012345",
    discord_username: "XboxWarlord#1111",
    discord_avatar: "https://cdn.discordapp.com/embed/avatars/5.png",
    ubisoft_id: "WarlordR6",
    rango: "Platinum III",
    kd: 0.98,
    rol_principal: "hard-breach",
    rol_secundario: "anchor",
    disponibilidad: "diaria",
    region: "na",
    idioma: "en",
    plataforma: "xbox",
    destacado: false,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  }
];

export const mockEquipos: Equipo[] = [
  {
    id: "eq1",
    capitan_id: "u1_cap",
    nombre_equipo: "BDS Esports",
    discord_id_capitan: "9876543210",
    discord_username_capitan: "BDS_Manager#1337",
    discord_avatar_capitan: "https://cdn.discordapp.com/embed/avatars/2.png",
    descripcion: "Roster profesional de R6 buscando un Flex/Support con experiencia en Tier 1 nacional. Entrenamientos diarios.",
    region: "eu-west",
    idioma: "fr/en",
    plataforma: "pc",
    rol_buscado: "flex",
    rango_medio: "Champion",
    kd_medio: 1.28,
    integrantes_ubisoft_ids: ["Shaiiko.BDS", "BriD.BDS", "Elemzje.BDS", "LikEfac.BDS"],
    destacado: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "eq2",
    capitan_id: "u2_cap",
    nombre_equipo: "x6tence R6",
    discord_id_capitan: "8765432109",
    discord_username_capitan: "FlipiN#2026",
    discord_avatar_capitan: "https://cdn.discordapp.com/embed/avatars/4.png",
    descripcion: "Club clásico español preparándose para la Liga Nacional. Buscamos un Entry Fragger agresivo y con excelente comunicación.",
    region: "eu-west",
    idioma: "es",
    plataforma: "pc",
    rol_buscado: "entry-fragger",
    rango_medio: "Diamond III",
    kd_medio: 1.18,
    integrantes_ubisoft_ids: ["Goga.PENTA", "Wesker.x6", "Jovial.x6", "Kryp.x6"],
    destacado: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "eq3",
    capitan_id: "u3_cap",
    nombre_equipo: "Xbox Apex Legends",
    discord_id_capitan: "7654321098",
    discord_username_capitan: "GamerDad#5555",
    discord_avatar_capitan: "https://cdn.discordapp.com/embed/avatars/0.png",
    descripcion: "Equipo amateur de consola para competir en torneos de fin de semana y subir rango. Buen rollo y seriedad media.",
    region: "latam",
    idioma: "es",
    plataforma: "xbox",
    rol_buscado: "anchor",
    rango_medio: "Gold II",
    kd_medio: 1.05,
    integrantes_ubisoft_ids: ["GamerDadR6", "MiniTobi", "PapiSiege"],
    destacado: false,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "eq4",
    capitan_id: "u4_cap",
    nombre_equipo: "M80 Esports",
    discord_id_capitan: "6543210987",
    discord_username_capitan: "M80_Coach#0001",
    discord_avatar_capitan: "https://cdn.discordapp.com/embed/avatars/1.png",
    descripcion: "North American Challenger roster pushing for Pro League. Looking for a dedicated Hard Breach / IGL player.",
    region: "na",
    idioma: "en",
    plataforma: "pc",
    rol_buscado: "hard-breach",
    rango_medio: "Diamond I",
    kd_medio: 1.22,
    integrantes_ubisoft_ids: ["Spoit.M80", "DiasLucas.M80", "Yoggah.M80", "GMZ.M80"],
    destacado: false,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  }
];
